--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/lenlenlL6/Oneblock-PM4
build-by-default: true
branches:
- main
projects:
  Oneblock-PM4:
    path: ""
    icon: "icon.png"
    lint: false
...
