name: Oneblock
main: lenlenlL6\oneblock\Oneblock
author:
 - lenlenlL6
 - BeeAZ
authors:
 - DoraOtaku
api: 4.0.0
version: 0.0.9
mcpe-protocol: 503
depends: [MultiWorld]

commands:
 oneblock:
  description: Oneblock Commands
  aliases: ["ob", "is"]
  permission: oneblock.command
  
permissions:
 oneblock.command:
  description: Allow the player use oneblock commands
  default: true
