name: Oneblock
main: lenlenlL6\oneblock\Oneblock
author: [lenlenlL6, BeeAZ]
api: 4.0.0
version: 0.1.0
depend: [MultiWorld]

permissions:
 oneblock.command.oneblock:
  description: Allow the player use oneblock commands
  default: true
