name: Oneblock
main: lenlenlL6\oneblock\Oneblock
authors: [lenlenlL6, DoraOtaku]
api: 4.0.0
version: 0.0.2
depends: [FormAPI, MultiWorld]

commands:
 oneblock:
  description: Oneblock Commands
  permission: oneblock.command
  
permissions:
 oneblock.command:
  description: Use Oneblock Command
  default: true