name: Oneblock
main: lenlenlL6\oneblock\Oneblock
author: [lenlenlL6, DoraOtaku, BeeAZZ]
api: 4.0.0
version: 0.0.5
depends: [MultiWorld]

commands:
 oneblock:
  description: Oneblock Commands
  permission: oneblock.command
  
permissions:
 oneblock.command:
  description: Allow the player use oneblock commands
  default: true
