# You can customize the blocks that can appear in the tiers here. 
# Format: id.meta
# The block list can be viewed at: https://www.digminecraft.com/lists/item_id_list_pe.php

1: #Tier 1
- "1.0"
- "2.0"
2:
- "4.0"
- "17.0"
- "17.1"
- "17.3"
- "162.1"
- "17.2"
- "56.0"
3:
- "4.0"
- "16.0"
- "56.0"
- "56.0" # Help rate out more
- "21.0"
- "73.0"
- "15.0"
- "14.0"
- "1.0"
- "129.0"
4:
- "4.0"
- "16.0"
- "56.0"
- "56.0" # Help rate out more
- "21.0"
- "73.0"
- "15.0"
- "14.0"
- "1.0"
- "129.0"
5:
- "4.0"
- "16.0"
- "56.0"
- "56.0" # Help rate out more
- "21.0"
- "73.0"
- "15.0"
- "14.0"
- "1.0"
- "129.0"
6:
- "4.0"
- "16.0"
- "56.0"
- "56.0" # Help rate out more
- "21.0"
- "73.0"
- "15.0"
- "14.0"
- "1.0"
- "129.0"
7:
- "4.0"
- "16.0"
- "56.0"
- "56.0" # Help rate out more
- "21.0"
- "73.0"
- "15.0"
- "14.0"
- "1.0"
- "129.0"
8:
- "4.0"
- "16.0"
- "56.0"
- "56.0" # Help rate out more
- "21.0"
- "73.0"
- "15.0"
- "14.0"
- "1.0"
- "129.0" 
9:
- "4.0"
- "16.0"
- "56.0"
- "56.0" # Help rate out more
- "21.0"
- "73.0"
- "15.0"
- "14.0"
- "1.0"
- "129.0" 
10:
- "4.0"
- "16.0"
- "56.0"
- "56.0" # Help rate out more
- "21.0"
- "73.0"
- "15.0"
- "14.0"
- "1.0"
- "129.0" 

# Chest Items
items: #id.meta.count
- "364.0.5"
- "278.0.1"
- "50.0.1"