---
tier:
 1:
  "4:0": 50 #"id.meta": probability
  "21:0": 50
  
lang:
 WAITING_CREATE_ISLAND: "§aCreating an island, please wait a moment..."
 ALREADY_HAVE_ISLAND: "§cYou already have an island"
 CREATE_ISLAND_COMPLETE: "§aSuccessfully creates island"
 NO_ISLAND: "§cYou don't have any islands"
 BACK_ISLAND: "§aReturned to your island"
 WORLD_IS_WRONG: "§c The world you're in doesn't fit" # Occurs when the player resets the respawn location to the wrong world.
 SET_NEW_RESPAWN_LOCATION: "§aNew respawn location created"
 DELETE_ISLAND: "§aSuccessfully deleted the island"
 ACCEPT_INVITATION: "§aYou have accepted {name}'s invitation"
 DECLINE_THE_INVITATION: "§aYou declined {name}'s invitation"
 FRIENDS_WITHOUT_ISLAND: "§cThis friend of yours doesn't have an island"
 TELEPORT_TO_FRIEND_ISLAND: "§aTeleported to {name}'s island"
 PLAYER_DOES_NOT_EXIST: "§cPlayer {name} is no longer online"
 TOO_MUCH_INVITATIONS: "§cPlayer {name} has too many invitations"
 THE_INVITATION_EXISTS: "§cYou have already sent an invitation to {name}"
 FRIEND_ALREADY_EXIST: "§cYou are already {name}'s friend"
 COMPLETED_SEND_INVITATIONS: "§aInvitation sent to {name}"
 DELETE_FRIENDS: "§aRemoved {name} from friends list"
 DO_NOT_HAVE_PERMISSION: "§cYou can't do this here"
 MAXIMUM_TIER: "§cYou have reached the limit of tier"
 UP_TIER: "§aYou have leveled up to tier {tier}"
...
